variables:
  GIT_DEPTH: "1"

image: continuumio/anaconda3:latest

before_script:
  - apt-get update
  - apt-get install -y pkg-config gcc python3 libhdf5-dev

build_job:
  tags:
    - docker-amd64-bigmem
  script:
    - chmod +x run_ci
    - source run_ci
