variables:
  GIT_DEPTH: "1"

image: docker pull nvidia/cuda

before_script:
  - apt-get update
  - apt-get install -y pkg-config gcc python3 libhdf5-dev

build_job:
  tags:
    - 2204-cuda-12.5
  script:
    - chmod +x run_ci
    - source run_ci