variables:
  GIT_DEPTH: "1"

image: aryannanda/cuda-conda:amd64

before_script:
  - apt-get update
  - apt-get install -y pkg-config gcc python3 libhdf5-dev

build_job:
  tags:
    - 2204-cuda-12.5
  script:
    - export TF_GPU_ALLOCATOR=cuda_malloc_async
    - chmod +x ../ci/run_ci
    - source ../ci/run_ci
