#!/bin/bash

set -e ; set -u

source ci_env

ENVFILE='environment.yml'

function process_notebook(){
    local path="$1"

    local filename="${path##*/}"
    local folder="${path%/*}"
    local basename="${filename%.*}"
    local envfile=''
    local envname=''
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    NC='\033[0m' # No Color    

    # Find the environment.yml file
    for location in "$folder/../../.." "$folder/../.." "$folder/.." "$folder" ; do
        if [ -f "$location/$ENVFILE" ]; then
            envfile="$location/$ENVFILE"
            # Extract the environment name from environment.yml
            envname=$(grep 'name:' "$envfile" | sed -e 's/.*: *//')
            break
        fi
    done

    printf "=====================\n"
    printf "Envfile:\t$envfile\n"
    printf "Envname:\t$envname\n"
    printf "Path:\t\t$path\n"
    printf "Filename:\t${filename}\n"
    printf "Folder:\t\t${folder}\n"
    printf "Basename:\t${basename}\n"
    printf "=====================\n"

    # Check if envname is not empty before attempting to update the environment
    if [ -n "$envname" ]; then
        conda env update --prune --quiet --name "$envname" --file "$envfile"
        convert_notebook "$envname" "$path"
    else
        echo "Error: Environment name not found in $envfile. Unable to update Conda environment."
        exit 1
    fi

    printf "${GREEN}====> PASSED:${NC} $path\n"
}


function convert_notebook() {
    (
    # Activate Conda environment
    set +u
    source activate $1
    set -u

    # Check GPU availability with TensorFlow
    gpu_devices=$(python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))")
    if [ -z "$gpu_devices" ]; then
        echo "No GPU devices found."
    else
        echo "GPU devices found: $gpu_devices"
    fi

    # Run notebook
    jupyter nbconvert --to notebook --execute \
    --ExecutePreprocessor.timeout=1200 \
    --output output.ipynb \
    "$2" || {  printf "${RED}====> FAILED:${NC} $2\n" ; exit 99 ; }
    )
}

if [ $# -eq 1 ]; then
    process_notebook "$1"
else
    notebookcount=0
    while read -d $'\0' path ; do
        # if the noci flag was passed, dont look for a noci file
        if [[ -f "${path%/*}/noci" ]] ; then
            echo "===> noci found for ${path##*/}. skipping it."
            continue
        fi
        process_notebook "$path"
        let notebookcount=notebookcount+1
    done < <(find . -name \*.ipynb -print0)
    echo The notebook count is "$notebookcount"
fi