# -*- coding: utf-8 -*-
"""audioFeatureExtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UO4nre6O-ir2ZcItR8T0uD8-nr1Oq91p
"""

import os
import sys
import ffmpeg
import numpy as np
import soundfile as sf
import resampy
import librosa
import tensorflow.compat.v1 as tf
from tensorflow.compat.v1 import GraphDef
from tensorflow.compat.v1 import gfile
from tensorflow.python.tools import freeze_graph

video_path = '/Users/Aryan/Movies/GSoC_Dataset/NonCommercial_Videos_Dataset/news0.mov'
output_audio_path = './extractedAudioFeatures.wav'

def create_vggish_frozen_graph():
    """Create the VGGish frozen graph if it doesn't already exist."""
    vggish_dir = './Vggish'
    output_graph_path = os.path.join(vggish_dir, 'vggish_new.pb')

    # Check if the directory exists
    if not os.path.exists(vggish_dir):
        os.makedirs(vggish_dir)

        # Clone the repository and create the frozen graph
        os.system('git clone https://github.com/tensorflow/models.git')
        sys.path.append('models/research/audioset/vggish/')

        import vggish_slim
        os.system('curl -O https://storage.googleapis.com/audioset/vggish_model.ckpt')
        ckpt_path = 'vggish_model.ckpt'

        with tf.Graph().as_default(), tf.compat.v1.Session() as sess:
            vggish_slim.define_vggish_slim(training=False)
            vggish_slim.load_vggish_slim_checkpoint(sess, ckpt_path)

            saver = tf.compat.v1.train.Saver(tf.compat.v1.global_variables())

            freeze_graph.freeze_graph_with_def_protos(
                sess.graph_def,
                saver.as_saver_def(),
                ckpt_path,
                'vggish/fc2/BiasAdd',
                restore_op_name=None,
                filename_tensor_name=None,
                output_graph=output_graph_path,
                clear_devices=True,
                initializer_nodes=None)

        os.system('rm -rf models/')
        os.system('rm %s' % ckpt_path)
        print(f'VGGish frozen graph created at {output_graph_path}')
    else:
        print(f'VGGish frozen graph already exists at {output_graph_path}')

def preprocess_audio(audio_path, target_sr=16000):
    """Load and preprocess audio data."""
    data, sr = sf.read(audio_path)

    if data.ndim > 1:
        data = np.mean(data, axis=1)  # Convert to mono if stereo

    # Check if audio length is sufficient
    if len(data) < target_sr:
        raise ValueError("Audio data is too short to process.")

    # Resample if needed
    if sr != target_sr:
        if len(data) < sr:
            raise ValueError("Audio data is too short for resampling.")
        data = resampy.resample(data, sr, target_sr)

    return data, target_sr

def compute_spectrogram(audio_data, sr, n_fft=2048, hop_length=512, n_mels=64):
    """Compute the log-mel spectrogram from audio data."""
    # Compute the STFT
    D = librosa.stft(audio_data, n_fft=n_fft, hop_length=hop_length)
    print("STFT shape:", D.shape)

    # Convert to mel scale
    mel_filter = librosa.filters.mel(sr=sr, n_fft=n_fft, n_mels=n_mels)
    print("Mel filter shape:", mel_filter.shape)

    # Compute Mel spectrogram
    mel_spectrogram = np.matmul(mel_filter, np.abs(D)**2)

    # Apply log transformation
    log_mel_spectrogram = np.log1p(mel_spectrogram)

    # Ensure shape matches VGGish input
    # Note: Adjust this step according to VGGish input requirements
    if log_mel_spectrogram.shape[0] != 96:
        # Adjust shape to (96, n_mels) if necessary, but handle resizing carefully
        log_mel_spectrogram = np.resize(log_mel_spectrogram, (96, n_mels))

    return log_mel_spectrogram

def extract_features_vggish(spectrogram):
    """Extract features using VGGish model."""
    with tf.Graph().as_default():
        graph_def = tf.compat.v1.GraphDef()
        with tf.io.gfile.GFile('./Vggish/vggish_new.pb', 'rb') as f:
            graph_def.ParseFromString(f.read())
            tf.import_graph_def(graph_def, name='')

        with tf.compat.v1.Session() as sess:
            # Use the correct tensor names found in the graph
            features_tensor = sess.graph.get_tensor_by_name('vggish/fc2/BiasAdd:0')
            input_tensor = sess.graph.get_tensor_by_name('vggish/input_features:0')

            # Add batch dimension and process
            spectrogram = np.expand_dims(spectrogram, axis=0)  # Add batch dimension
            features = sess.run(features_tensor, feed_dict={input_tensor: spectrogram})
            return features

def extract_audio_from_video(video_path, audio_path):
    """Extract audio from video and save to file."""
    if os.path.exists(audio_path):
        os.remove(audio_path)
    command = f"ffmpeg -i {video_path} -q:a 0 -map a {audio_path}"
    os.system(command)

def quantize_features(features_matrix, n_bits=8):
    """Quantize features to 8-bit integers."""
    min_val = np.min(features_matrix)
    max_val = np.max(features_matrix)

    # Normalize features to range [0, 1]
    normalized_features = (features_matrix - min_val) / (max_val - min_val)

    # Quantize to 8-bit integers
    quantized_features = (normalized_features * 255).astype(np.uint8)

    return quantized_features

def extract_audio_features(video_path, target_duration=10):
    """Extract audio features from video and generate 128-dimensional embeddings."""
    audio_path = 'temp_audio.wav'
    extract_audio_from_video(video_path, audio_path)

    audio_data, sr = preprocess_audio(audio_path)

    # Ensure audio is long enough
    if len(audio_data) < sr * target_duration:
        raise ValueError("Audio data is shorter than target duration.")

    features_list = []
    for start_time in range(0, target_duration):
        start_sample = start_time * sr
        end_sample = (start_time + 1) * sr
        segment = audio_data[start_sample:end_sample]

        # Compute log-mel spectrogram
        spectrogram = compute_spectrogram(segment, sr)

        # Extract features using VGGish
        features = extract_features_vggish(spectrogram)
        features_list.append(features[0])

    features_matrix = np.array(features_list)

    # Normalize features
    quantized_features = quantize_features(features_matrix)

    return quantized_features

# Example usage
video_path = video_path
features_matrix = extract_audio_features(video_path)

print(features_matrix)

min_value = np.min(features_matrix)
max_value = np.max(features_matrix)

print(min_value)
print(max_value)